export const data = [
  {
    employer_company_type: "Mining",
    employer_logo:
      "https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=100076443144431",
    employer_name: "Seneca Resources",
    employer_website: "http://www.natfuel.com",
    job_apply_is_direct: false,
    job_apply_link:
      "https://www.linkedin.com/jobs/view/react-developer-full-stack-at-seneca-resources-3643968217",
    job_apply_quality_score: 0.586,
    job_benefits: null,
    job_city: null,
    job_country: "US",
    job_description:
      "Our client is a rapidly growing, entrepreneurial, multi-faceted consulting company is seeking a Full Stack React developer to support a federal government entity. They are looking to add an independent, energetic, and self-motivated React developer to an established team working on a federal government project. It’s a small team of developers with support from matrixed staff in other roles. They look for someone who loves to learn and is passionate about keeping up to date with industry trends and technology. This developer will participate in building and modernizing web-based applications to support our projects, work with technical leads to develop and enforce standards, collaborate with a development team, and follow solutions as they are developed through production deployment. The team performs custom software development to modernize siloed, legacy applications using modular design standards. The team works closely with clients and other contractors to ensure the performance and reliability of public-facing, mission-critical applications. What you’ll be doing: • Identifies requirements by establishing personal rapport with potential and actual clients and with other persons in a position to understand service requirements • Develops and maintains applications and databases by evaluating client needs; analyzing requirements; developing software systems • Bug fixing, browser testing, accessibility testing • Documenting code and processes • Collaborate with designers, developers, and project managers on client work • Communicating with co-workers about your projects and tasks • Actively participate in project discussions and team meetings (e.g., daily standups, code reviews) Minimum Qualifications: • BS in computer science or related field • 3+ years of experience building full-stack applications using JavaScript technologies • 3+ years of experience with React development • Ability to obtain and maintain a Public Trust Preferred Qualifications: • Experience with Node.js • Experience with GraphQL • Experience with Cloud architecture such as AWS • Proficient with Git and GitHub • Highly proficient in HTML 5, CSS 3.0, JavaScript, REST Concepts, JWT • Proficient understanding of cross-browser compatibility issues and ways to work around them Technologies/tools you’ll use: • AWS services (S3, CloudFront, Lambda, API Gateway, RDS) • GitHub • MySQL • React • Node.js • GraphQL/Rest • JavaScript, HTML, CSS • Gatsby • Knex.js • Cypress",
    job_employment_type: "FULLTIME",
    job_experience_in_place_of_education: false,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=GJC1rxqaS_4AAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "They look for someone who loves to learn and is passionate about keeping up to date with industry trends and technology",
        "BS in computer science or related field",
        "3+ years of experience building full-stack applications using JavaScript technologies",
        "3+ years of experience with React development",
        "Ability to obtain and maintain a Public Trust",
        "AWS services (S3, CloudFront, Lambda, API Gateway, RDS)",
        "MySQL",
        "Node.js",
        "GraphQL/Rest",
        "JavaScript, HTML, CSS",
      ],
      Responsibilities: [
        "This developer will participate in building and modernizing web-based applications to support our projects, work with technical leads to develop and enforce standards, collaborate with a development team, and follow solutions as they are developed through production deployment",
        "The team performs custom software development to modernize siloed, legacy applications using modular design standards",
        "The team works closely with clients and other contractors to ensure the performance and reliability of public-facing, mission-critical applications",
        "Identifies requirements by establishing personal rapport with potential and actual clients and with other persons in a position to understand service requirements",
        "Develops and maintains applications and databases by evaluating client needs; analyzing requirements; developing software systems",
        "Bug fixing, browser testing, accessibility testing",
        "Documenting code and processes",
        "Collaborate with designers, developers, and project managers on client work",
        "Communicating with co-workers about your projects and tasks",
        "Actively participate in project discussions and team meetings (e.g., daily standups, code reviews)",
      ],
    },
    job_id: "GJC1rxqaS_4AAAAAAAAAAA==",
    job_is_remote: true,
    job_job_title: null,
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_max_salary: null,
    job_min_salary: null,
    job_naics_code: "211111",
    job_naics_name: "Crude Petroleum and Natural Gas Extraction",
    job_offer_expiration_datetime_utc: "2023-07-23T15:00:47.000Z",
    job_offer_expiration_timestamp: 1690124447,
    job_onet_job_zone: "4",
    job_onet_soc: "15113300",
    job_posted_at_datetime_utc: "2023-06-23T15:00:47.000Z",
    job_posted_at_timestamp: 1687532447,
    job_posting_language: "en",
    job_publisher: "LinkedIn",
    job_required_education: {
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      high_school: false,
      postgraduate_degree: false,
      professional_certification: false,
      professional_certification_mentioned: false,
    },
    job_required_experience: {
      experience_mentioned: true,
      experience_preferred: false,
      no_experience_required: false,
      required_experience_in_months: 36,
    },
    job_required_skills: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_state: null,
    job_title: "React Developer (Full Stack)",
  },
  {
    employer_company_type: null,
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRygkWgtoBaj5P-zKh_SmkffPP6vySFjIMf26W1&s=0",
    employer_name: "Rework IT Development",
    employer_website: null,
    job_apply_is_direct: true,
    job_apply_link:
      "https://wellfound.com/company/rework-it-development/jobs/2716559-react-developer",
    job_apply_quality_score: 0.5833,
    job_benefits: null,
    job_city: "Comitán de Domínguez",
    job_country: "MX",
    job_description: "Hey guys this is a sweet job",
    job_employment_type: "FULLTIME",
    job_experience_in_place_of_education: false,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=oP2eWfICitcAAAAAAAAAAA%3D%3D",
    job_highlights: {},
    job_id: "oP2eWfICitcAAAAAAAAAAA==",
    job_is_remote: true,
    job_job_title: null,
    job_latitude: 16.22996,
    job_longitude: -92.11557,
    job_max_salary: 33000,
    job_min_salary: 33000,
    job_offer_expiration_datetime_utc: "2023-09-23T18:58:50.000Z",
    job_offer_expiration_timestamp: 1695495530,
    job_onet_job_zone: "3",
    job_onet_soc: "15113400",
    job_posted_at_datetime_utc: "2023-06-23T18:58:47.000Z",
    job_posted_at_timestamp: 1687546727,
    job_posting_language: "en",
    job_publisher: "Wellfound",
    job_required_education: {
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      high_school: false,
      postgraduate_degree: false,
      professional_certification: false,
      professional_certification_mentioned: false,
    },
    job_required_experience: {
      experience_mentioned: true,
      experience_preferred: false,
      no_experience_required: false,
      required_experience_in_months: 36,
    },
    job_required_skills: null,
    job_salary_currency: "USD",
    job_salary_period: "YEAR",
    job_state: "Chis.",
    job_title: "React Developer",
  },
  {
    employer_company_type: null,
    employer_logo: null,
    employer_name: "AMS IT Solutions LLC",
    employer_website: null,
    job_apply_is_direct: true,
    job_apply_link:
      "https://www.dice.com/job-detail/fa1fd3a9-00ae-430c-b18c-5ad881055fe7",
    job_apply_quality_score: 0.5639,
    job_benefits: null,
    job_city: "Bentonville",
    job_country: "US",
    job_description: "Another job description this is nice",
    job_employment_type: "CONTRACTOR",
    job_experience_in_place_of_education: false,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=wKTi6xUM0PEAAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "Minimum of 5 years experience in JavaScript and TypeScript",
        "Experience supporting sites on different browsers, operating systems, and devices",
        "Advanced knowledge in React-based patterns",
        "Knowledge of Next.js React framework",
        "Experience in Agile Kanban and Scrum development frameworks",
        "Experience establishing repeatable code practices and standards",
        "Experience facilitating technical decisions & discussions with other developers",
        "Experience with Test-Driven Development using Cucumber or equivalent frameworks",
        "Experience implementing mock interfaces for testing",
        "Strong interpersonal and communication skills",
      ],
    },
    job_id: "wKTi6xUM0PEAAAAAAAAAAA==",
    job_is_remote: false,
    job_job_title: null,
    job_latitude: 36.372356,
    job_longitude: -94.21021,
    job_max_salary: null,
    job_min_salary: null,
    job_offer_expiration_datetime_utc: "2023-07-23T13:24:48.000Z",
    job_offer_expiration_timestamp: 1690118688,
    job_onet_job_zone: "3",
    job_onet_soc: "15113400",
    job_posted_at_datetime_utc: "2023-06-22T13:24:48.000Z",
    job_posted_at_timestamp: 1687440288,
    job_posting_language: "en",
    job_publisher: "Dice",
    job_required_education: {
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      high_school: false,
      postgraduate_degree: false,
      professional_certification: false,
      professional_certification_mentioned: false,
    },
    job_required_experience: {
      experience_mentioned: true,
      experience_preferred: false,
      no_experience_required: false,
      required_experience_in_months: 60,
    },
    job_required_skills: ["React js", "Javascript", "Type Script", "etc..."],
    job_salary_currency: null,
    job_salary_period: null,
    job_state: "AR",
    job_title: "React js Developer",
  },
];
